from __future__ import annotations

import asyncio
import json
import time
from uuid import uuid4

from langchain_core.exceptions import OutputParserException

from app.schemas.codebook import CodebookSchema, GeneratedCodebookResponse
from app.schemas.llm import (
    GeneratedCodeSuggestion,
    GeneratedThemeNode,
    GeneratedThemePath,
    PassageCodebookGeneration,
)

API_INGESTION = "/api/v1/ingestion"
API_CODEBOOKS = "/api/v1/codebooks"
CORPUS_ID = "00000000-0000-0000-0000-000000000222"


async def _create_corpus_with_docs(client, texts: list[str]) -> tuple[str, list[str]]:
    corpus_response = await client.post(
        f"{API_INGESTION}/corpora",
        json={"corpus_id": CORPUS_ID, "name": "Generation Job Corpus"},
    )
    assert corpus_response.status_code == 201
    corpus_id = corpus_response.json()["data"]["id"]

    ingest_response = await client.post(
        f"{API_INGESTION}/corpora/{corpus_id}/documents/bulk",
        json={
            "documents": [
                {"title": f"Doc {idx}", "text": text}
                for idx, text in enumerate(texts, start=1)
            ]
        },
    )
    assert ingest_response.status_code == 201

    document_response = await client.get(f"{API_INGESTION}/corpora/{corpus_id}/documents")
    assert document_response.status_code == 200
    document_ids = [row["id"] for row in document_response.json()["data"]["items"]]
    return corpus_id, document_ids


async def _wait_for_terminal_job_status(client, job_id: str, timeout_seconds: float = 10.0) -> dict:
    started = time.monotonic()
    last_payload: dict = {}
    while time.monotonic() - started < timeout_seconds:
        response = await client.get(f"{API_CODEBOOKS}/generate-jobs/{job_id}")
        assert response.status_code == 200
        payload = response.json()["data"]
        last_payload = payload
        if payload["status"] in {"succeeded", "failed", "cancelled"}:
            return payload
        await asyncio.sleep(0.25)
    raise AssertionError(f"Job {job_id} did not reach terminal status. Last payload: {last_payload}")


def _patch_batched_generation(monkeypatch, single_passage_fn) -> None:
    async def _fake_generate_codebook(self, **kwargs) -> GeneratedCodebookResponse:
        on_phase = kwargs.get("on_phase")
        on_progress = kwargs.get("on_progress")
        should_cancel = kwargs.get("should_cancel")
        if on_phase is not None:
            await on_phase("extracting_quote_codes")
        transcript_document_ids = kwargs.get("transcript_document_ids") or []
        documents_processed = len(transcript_document_ids) if transcript_document_ids else 2
        if on_progress is not None:
            await on_progress(0, documents_processed)

        failed_passages: list[GeneratedCodebookResponse.PassageFailure] = []
        try:
            single_passage_fn("Alpha transcript about collaboration and adaptation.")
        except Exception as exc:
            failed_passages.append(
                GeneratedCodebookResponse.PassageFailure(
                    passage_index=0,
                    passage_excerpt="Alpha transcript about collaboration and adaptation.",
                    error=str(exc),
                    attempts=3,
                )
            )

        for done in range(1, documents_processed + 1):
            if should_cancel is not None and await should_cancel():
                from app.services.codebook_generation import CodebookGenerationCancelledError

                raise CodebookGenerationCancelledError("cancelled")
            if on_progress is not None:
                await on_progress(done, documents_processed)

        if on_phase is not None:
            await on_phase("persisting_codebook")
        return GeneratedCodebookResponse(
            codebook=CodebookSchema(
                id=uuid4(),
                corpus_id=kwargs["corpus_id"],
                name=kwargs["codebook_name"],
                description="Generated by test stub",
                version=1,
                created_by="system-llm",
                research_query=kwargs.get("research_query"),
                researcher_topics=kwargs.get("researcher_topics"),
            ),
            application_run_id=uuid4() if kwargs.get("apply_after_generation", True) else None,
            transcripts_processed=documents_processed,
            passages_processed=documents_processed,
            themes_created=1,
            codes_created=1,
            documents_coded=documents_processed,
            documents_failed=0,
            quotes_created=max(1, documents_processed),
            passages_failed=len(failed_passages),
            failed_passages=failed_passages,
            provenance={"metrics": {"code_reusability": 1.0}},
            action_log=[{"action": "test_stub"}],
        )

    monkeypatch.setattr(
        "app.services.codebook_generation.CodebookGenerationService.generate_codebook",
        _fake_generate_codebook,
    )


async def test_generate_codebook_job_completes_successfully(client, monkeypatch) -> None:
    corpus_id, document_ids = await _create_corpus_with_docs(
        client,
        texts=[
            "Alpha workflow has repeated manual handoffs and rework.",
            "Beta onboarding lacks clarity and causes delays.",
        ],
    )

    def _fake_generate_codebook_for_passage(_: str, **_kwargs) -> PassageCodebookGeneration:
        return PassageCodebookGeneration(
            themes=[
                GeneratedThemePath(
                    path=[
                        GeneratedThemeNode(label="Workflow Friction"),
                        GeneratedThemeNode(label="Manual Work"),
                    ]
                )
            ],
            codes=[
                GeneratedCodeSuggestion(
                    label="Manual Bottleneck",
                    description="Manual processing slows progress.",
                    theme_path=["Workflow Friction", "Manual Work"],
                )
            ],
        )

    _patch_batched_generation(monkeypatch, _fake_generate_codebook_for_passage)

    create_response = await client.post(
        f"{API_CODEBOOKS}/generate-jobs",
        json={
            "codebook_name": "Generated Async",
            "corpus_id": corpus_id,
            "transcript_document_ids": document_ids,
            "research_query": "How do participants describe workflow friction and manual bottlenecks?",
        },
    )
    assert create_response.status_code == 202
    created_job = create_response.json()["data"]
    assert created_job["status"] in {"queued", "running"}
    assert "progress_percent" in created_job
    assert "phase" in created_job

    terminal_job = await _wait_for_terminal_job_status(client, created_job["id"])
    assert terminal_job["status"] == "succeeded", terminal_job.get("error_message")
    assert terminal_job["progress_percent"] == 100
    assert terminal_job["phase"] == "succeeded"
    assert terminal_job["codebook_id"] is not None
    assert terminal_job["themes_created"] >= 1
    assert terminal_job["codes_created"] >= 1


async def test_generate_codebook_job_accepts_payload_without_confirmation_field(client, monkeypatch) -> None:
    corpus_id, document_ids = await _create_corpus_with_docs(
        client,
        texts=["Short transcript about operations and delays."],
    )

    def _fake_generate_codebook_for_passage(_: str, **_kwargs) -> PassageCodebookGeneration:
        return PassageCodebookGeneration(
            themes=[GeneratedThemePath(path=[GeneratedThemeNode(label="Operations")])],
            codes=[GeneratedCodeSuggestion(label="Delay", description=None, theme_path=["Operations"])],
        )

    _patch_batched_generation(monkeypatch, _fake_generate_codebook_for_passage)

    response = await client.post(
        f"{API_CODEBOOKS}/generate-jobs",
        json={
            "codebook_name": "Generated Async",
            "corpus_id": corpus_id,
            "transcript_document_ids": document_ids,
            "research_query": "How do participants describe workflow friction and manual bottlenecks?",
        },
    )
    assert response.status_code == 202
    assert response.json()["success"] is True


async def test_generate_codebook_job_can_be_cancelled_while_running(client, monkeypatch) -> None:
    long_text = " ".join(f"token{i}" for i in range(0, 260))
    corpus_id, document_ids = await _create_corpus_with_docs(client, texts=[long_text])

    def _slow_generate_codebook_for_passage(_: str, **_kwargs) -> PassageCodebookGeneration:
        time.sleep(0.03)
        return PassageCodebookGeneration(
            themes=[
                GeneratedThemePath(
                    path=[
                        GeneratedThemeNode(label="Operations"),
                    ]
                )
            ],
            codes=[
                GeneratedCodeSuggestion(
                    label="Ops Note",
                    description=None,
                    theme_path=["Operations"],
                )
            ],
        )

    _patch_batched_generation(monkeypatch, _slow_generate_codebook_for_passage)

    create_response = await client.post(
        f"{API_CODEBOOKS}/generate-jobs",
        json={
            "codebook_name": "Generated Async Cancel",
            "corpus_id": corpus_id,
            "transcript_document_ids": document_ids,
            "research_query": "How do participants describe workflow friction and manual bottlenecks?",
        },
    )
    assert create_response.status_code == 202
    created_job = create_response.json()["data"]

    cancel_response = await client.post(
        f"{API_CODEBOOKS}/generate-jobs/{created_job['id']}/cancel",
    )
    assert cancel_response.status_code in {202, 422}
    terminal_job = await _wait_for_terminal_job_status(client, created_job["id"])
    # Cancellation is best-effort; depending on timing the job may complete, cancel,
    # or surface an execution failure from the worker.
    assert terminal_job["status"] in {"succeeded", "cancelled", "failed"}


async def test_generate_codebook_job_uses_all_corpus_documents_when_ids_omitted(client, monkeypatch) -> None:
    corpus_id, _ = await _create_corpus_with_docs(
        client,
        texts=[
            "First transcript about collaboration.",
            "Second transcript about process and communication.",
        ],
    )

    def _fake_generate_codebook_for_passage(_: str, **_kwargs) -> PassageCodebookGeneration:
        return PassageCodebookGeneration(
            themes=[GeneratedThemePath(path=[GeneratedThemeNode(label="Collaboration")])],
            codes=[GeneratedCodeSuggestion(label="Team Alignment", description=None, theme_path=["Collaboration"])],
        )

    _patch_batched_generation(monkeypatch, _fake_generate_codebook_for_passage)

    response = await client.post(
        f"{API_CODEBOOKS}/generate-jobs",
        json={
            "codebook_name": "Generated Async All Docs",
            "corpus_id": corpus_id,
            "research_query": "How do participants describe workflow friction and manual bottlenecks?",
        },
    )
    assert response.status_code == 202
    created_job = response.json()["data"]

    terminal_job = await _wait_for_terminal_job_status(client, created_job["id"])
    assert terminal_job["status"] == "succeeded"
    assert terminal_job["transcripts_processed"] == 2


async def test_generate_codebook_job_records_partial_parse_failures_and_succeeds(client, monkeypatch) -> None:
    corpus_id, document_ids = await _create_corpus_with_docs(
        client,
        texts=[
            "Alpha transcript about collaboration and adaptation.",
            "Beta transcript about planning and process.",
        ],
    )
    calls_by_passage: dict[str, int] = {}

    def _sometimes_fails_generate_codebook_for_passage(passage: str) -> PassageCodebookGeneration:
        calls_by_passage[passage] = calls_by_passage.get(passage, 0) + 1
        if "Alpha" in passage and calls_by_passage[passage] <= 3:
            raise OutputParserException("Invalid json output: malformed")
        return PassageCodebookGeneration(
            themes=[GeneratedThemePath(path=[GeneratedThemeNode(label="Collaboration")])],
            codes=[GeneratedCodeSuggestion(label="Team Alignment", description=None, theme_path=["Collaboration"])],
        )

    _patch_batched_generation(monkeypatch, _sometimes_fails_generate_codebook_for_passage)

    response = await client.post(
        f"{API_CODEBOOKS}/generate-jobs",
        json={
            "codebook_name": "Generated Async Partial Parse Failure",
            "corpus_id": corpus_id,
            "transcript_document_ids": document_ids,
            "research_query": "How do participants describe workflow friction and manual bottlenecks?",
        },
    )
    assert response.status_code == 202
    created_job = response.json()["data"]

    terminal_job = await _wait_for_terminal_job_status(client, created_job["id"])
    assert terminal_job["status"] == "succeeded"
    assert terminal_job["error_message"] is not None
    warning = json.loads(terminal_job["error_message"])
    assert warning["type"] == "passage_generation_partial_failures"
    assert warning["passages_failed"] == 1
    assert len(warning["failed_passages"]) == 1


async def test_list_generation_jobs_filters_by_corpus_and_status(client, db_session) -> None:
    # Insert jobs directly (no runner/LLM) and assert the list endpoint scopes
    # by corpus and honours the comma-separated status filter. This backs the
    # server-rendered "running" rows on the codebook list page.
    from uuid import UUID

    from app.models import CodebookGenerationJob

    corpus = UUID(CORPUS_ID)
    other_corpus = UUID("00000000-0000-0000-0000-0000000009ff")
    db_session.add_all([
        CodebookGenerationJob(status="running", codebook_name="Running One",
                              corpus_id=corpus, transcript_document_ids_json="[]"),
        CodebookGenerationJob(status="queued", codebook_name="Queued One",
                              corpus_id=corpus, transcript_document_ids_json="[]"),
        CodebookGenerationJob(status="succeeded", codebook_name="Done One",
                              corpus_id=corpus, transcript_document_ids_json="[]"),
        CodebookGenerationJob(status="running", codebook_name="Other Corpus",
                              corpus_id=other_corpus, transcript_document_ids_json="[]"),
    ])
    await db_session.commit()

    # No status filter → every job for the corpus, and only that corpus.
    response = await client.get(
        f"{API_CODEBOOKS}/generate-jobs", params={"corpus_id": CORPUS_ID}
    )
    assert response.status_code == 200
    names = {job["codebook_name"] for job in response.json()["data"]}
    assert names == {"Running One", "Queued One", "Done One"}

    # Status filter → only the active jobs.
    response = await client.get(
        f"{API_CODEBOOKS}/generate-jobs",
        params={"corpus_id": CORPUS_ID, "status": "queued,running"},
    )
    assert response.status_code == 200
    active = {job["codebook_name"] for job in response.json()["data"]}
    assert active == {"Running One", "Queued One"}
